version: "3.8"

services:
  web:
    build:
      context: ./car-management
    container_name: fastapi_project
    ports:
      - "8000:80"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_fastapi
    environment:
      POSTGRES_USER: zrch
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_management
    ports:
      - "5432:5432"
